name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # this step must happen so that the code is available
    - uses: actions/checkout@v4

    - name: where am i
      run: pwd

    - name: what exists
      run: ls -hal

    - name: use container
      uses: perfect-python/perfect-python@v4
