name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-my-project:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    # this step must happen so that the code is available
    - uses: actions/checkout@v4

    - name: where am i
      run: pwd
      timeout-minutes: 1

    - name: what exists
      run: ls -hal
      timeout-minutes: 1

    - name: use container
      uses: ./.github/actions/create_docker_image.yml
