name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: use container
      uses: perfect-python

    - name: python version
      run: python3 --version

    - name: Run check
      run: cd completed_script/ && make black
